@rootUrl=http://localhost:3000/

### GET
GET {{rootUrl}}

### POST
POST {{rootUrl}}regist

{
    "loginId": "dummy",
    "password": "dummy",
    "date": {
        "from": "2020-06-01", 
        "to": "2020-06-01"
    },
    "stepsRange": {
        "from": "8000",
        "to": "12000"
    }
};